### ISSUE TITLE
StorageBackend#updateCdmiObject has two capability URIs

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/cdmi-spi#11]
The api call should have only one capability URI in the call.  The plugin must know the current capability URI, since `#getCurrentStatus` returns `CdmiObjectStatus`, which has `CdmiObjectStatus#getCurrentCapabilitiesUri`.

**Comment by bertl4398** [comment]
i don't see any disadvantage of having both urls

**Comment by paulmillar** [comment]
It adds nothing (the value comes from the plugin) and makes correct behaviour unclear.
