### ISSUE TITLE
BackendCapability has Map<String,String>

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/cdmi-spi#12]
BackendCapability, which describes a specific capability, needs to know which capabilities are allowed for a transition.  This suggests the field member should be `List<String>` and not `Map<String,String>`

**Comment by bertl4398** [comment]
i don't see any disadvantage of having a map here

**Comment by paulmillar** [comment]
Sorry, I may have misunderstood the meaning of this field member -- please add JavaDoc to clarify
